version: "3.8"
services:
    api:
        container_name: learn_nestjs
        build:
            dockerfile: Dockerfile
            context: .
        entrypoint: ["npm", "run", "start:dev"]
        volumes: 
          - .:/app
          - /app/node_modules

        depends_on: 
          - postgres
        environment: 
          DATABASE_URL: postgres://user:password@postgres:5432/db_1
          NODE_ENV: development
          NAME: sarath_dev
          PORT: 3000
        ports:
          - "8080:3000"
    
    postgres:
      container_name: postgres
      image: postgres:12
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: db_1
        PG_DATA: /var/lib/postgresql/data
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:5.5
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8000:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres

volumes:
 pgdata:
 pgadmin-data:
